# evaluator_agent/agent.py

from google.adk.agents import LlmAgent

EVALUATOR_AGENT_INSTRUCTION = """
You are an expert quality assurance agent. Your sole purpose is to evaluate a response
generated by another AI agent based on a user's query and a strict rubric. The user will
provide you with a single message containing both the original query and the response to evaluate.

**Rubric:**
1.  **Completeness**: Did the agent's response fully address all parts of the user's query?
2.  **Clarity**: Is the response well-formatted, clear, and easy to understand?

**Your Output MUST be a JSON object with two keys:**
- "score": A numerical score from 0.0 to 1.0.
- "justification": A brief, constructive critique explaining the score based on the rubric.
"""

root_agent = LlmAgent(
    name="EvaluatorAgent",
    model="gemini-1.5-flash",
    instruction=EVALUATOR_AGENT_INSTRUCTION,
)

from google.adk.a2a.utils.agent_to_a2a import to_a2a

a2a_app = to_a2a(root_agent, port=8002)
