# kubernetes-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: galatic-streamhub
  namespace: default
  labels:
    app: galatic-streamhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: galatic-streamhub
  template:
    metadata:
      labels:
        app: galatic-streamhub
    spec:
      serviceAccountName: galatic-streamhub-ksa # Ensure this KSA is set up for Workload Identity
      containers:
      - name: galatic-streamhub-1
        # --- IMPORTANT: Update to your new image SHA ---
        image: us-central1-docker.pkg.dev/<YOUR_GCP_PROJECT_ID>/cloud-run-source-deploy/galatic-streamhub@sha256:c17354104fe64f488099297bf6689577298349046097233e56f37ec8490fbdba
        ports:
        - containerPort: 8080
          name: http1
        env:
        - name: GOOGLE_GENAI_USE_VERTEXAI
          value: '1'
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: google-api-credentials # From your K8s secret
              key: apiKey
        - name: GOOGLE_CLOUD_PROJECT
          value: <YOUR_GCP_PROJECT_ID> # Matches your Cloud Run config
        - name: GOOGLE_CLOUD_LOCATION
          value: us-central1 # Matches your Cloud Run config
        - name: mongodb-uri
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials # From your K8s secret
              key: uri
        - name: MULTIMODAL_MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: multimodal-mongodb-credentials # From your K8s secret
              key: uri
        # --- UPDATED: GOOGLE_MAPS_API_KEY from K8s Secret ---
        - name: GOOGLE_MAPS_API_KEY
          valueFrom:
            secretKeyRef:
              name: google-maps-api-key-k8s # From your K8s secret
              key: mapsApiKey
        # --- NEW: FIREBASE_PROJECT_ID ---
        - name: FIREBASE_PROJECT_ID
          value: <YOUR_FIREBASE_PROJECT_ID> # From your Cloud Run config
        resources:
          limits:
            cpu: "1000m"
            memory: "4G"
          requests: # Ensure these are set for Autopilot
            cpu: "500m"
            memory: "2G"
        startupProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 1
          periodSeconds: 240
          timeoutSeconds: 240
